import React, { useState, useCallback } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAdmin } from '../../context/AdminContext';
import InvoicePrint from '../../components/admin/InvoicePrint';
import { PREMIUM_STONES } from '../../data/stones';

// ── Client-side helpers (mirrors server logic for live preview) ───────────────

function getFY(date) {
  const d = new Date(date);
  const month = d.getMonth() + 1;
  const year  = d.getFullYear();
  const fyStart = month >= 4 ? year : year - 1;
  return `${fyStart}-${String(fyStart + 1).slice(-2)}`;
}

function deriveTaxType(buyerStateCode, sellerStateCode = '37') {
  return String(buyerStateCode) === String(sellerStateCode) ? 'CGST_SGST' : 'IGST';
}

const ones = ['','ONE','TWO','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE','TEN','ELEVEN','TWELVE','THIRTEEN','FOURTEEN','FIFTEEN','SIXTEEN','SEVENTEEN','EIGHTEEN','NINETEEN'];
const tens  = ['','','TWENTY','THIRTY','FORTY','FIFTY','SIXTY','SEVENTY','EIGHTY','NINETY'];
function belowHundred(n)  { return n < 20 ? ones[n] : tens[Math.floor(n/10)] + (n%10 ? ' '+ones[n%10] : ''); }
function belowThousand(n) { return n<100 ? belowHundred(n) : ones[Math.floor(n/100)]+' HUNDRED'+(n%100 ? ' '+belowHundred(n%100) : ''); }
function intToWords(n) {
  if (n === 0) return 'ZERO';
  let r = '';
  if (n >= 1e7)    { r += intToWords(Math.floor(n/1e7))  + ' CRORE ';    n %= 1e7; }
  if (n >= 100000) { r += intToWords(Math.floor(n/1e5))  + ' LAKH ';     n %= 1e5; }
  if (n >= 1000)   { r += belowThousand(Math.floor(n/1e3)) + ' THOUSAND '; n %= 1e3; }
  if (n > 0)       { r += belowThousand(n); }
  return r.trim();
}
function amountInWords(amount) {
  const rupees = Math.floor(amount);
  const paise  = Math.round((amount - rupees) * 100);
  let w = intToWords(rupees) + ' RUPEES';
  if (paise > 0) w += ' AND ' + intToWords(paise) + ' PAISE';
  return w + ' ONLY';
}

// ── Default state ─────────────────────────────────────────────────────────────

const today = new Date().toISOString().split('T')[0];

const defaultItem = () => ({ hsnCode: '', description: '', qty: '', unit: 'Sqm', rate: '', amount: 0 });

const defaultForm = {
  invoiceNumber:  '',          // empty = auto-generated by server
  customInvoice:  false,       // UI flag: is user manually entering an invoice number?
  invoiceDate:    today,
  copyType:       'ORIGINAL FOR RECIPIENT',
  poNumber:       '',
  transportMode:  'By Lorry',
  vehicleNumber:  '',
  placeOfSupply:  '',
  buyer:          { name: '', address: '', state: '', stateCode: '', gstin: '' },
  consignee:      { name: '', address: '', state: '', stateCode: '', gstin: '' },
  sameAsbuyer:    false,
  lineItems:      [defaultItem()],
  packing:        { totalCrates: '', piecesPerCrate: '' },
  taxRate:        18,
  notes:          '',
};

// ── SELLER constants (client copy for preview) ────────────────────────────────

const SELLER = {
  name: 'SWAMY SLABS INDUSTRIES',
  tagline: 'Mfrs. Of : Rough & Black Polished Slabs',
  address: 'BETAMCHERLA - 518599. Kurnool Dist. A.P.',
  gstin: '37FEIPKS873Q1ZF',
  email: 'swamyslabsindustries@gmail.com',
  phone: '9490238301',
  stateCode: '37',
};

// ── Shared input style ────────────────────────────────────────────────────────
const inp = {
  padding: '9px 12px', borderRadius: '7px',
  border: '1px solid #d6d3d1', fontSize: '13px',
  width: '100%', boxSizing: 'border-box', outline: 'none',
  background: '#fff', color: '#1c1917',
};
const label = { fontSize: '11px', fontWeight: '700', color: '#78716c', textTransform: 'uppercase', letterSpacing: '0.08em', display: 'block', marginBottom: '5px' };
const section = { background: '#fff', borderRadius: '12px', padding: '24px 28px', marginBottom: '20px', boxShadow: '0 1px 6px rgba(0,0,0,0.06)' };
const sectionTitle = { fontSize: '13px', fontWeight: '800', color: '#292524', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '18px', paddingBottom: '10px', borderBottom: '1px solid #f5f5f4' };
const grid2 = { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' };
const grid3 = { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px' };

// ── Component ─────────────────────────────────────────────────────────────────

export default function InvoiceFormPage() {
  const { authFetch, logout } = useAdmin();
  const navigate = useNavigate();

  const [form, setForm]           = useState(defaultForm);
  const [showPreview, setShowPreview] = useState(false);
  const [submitting, setSubmitting]   = useState(false);
  const [error, setError]             = useState('');

  // ── Computed preview data ────────────────────────────────────────────────
  const computedItems = form.lineItems.map(it => ({
    ...it,
    amount: Math.round(Number(it.qty || 0) * Number(it.rate || 0) * 100) / 100,
  }));
  const taxableValue = computedItems.reduce((s, i) => s + i.amount, 0);
  const taxType      = deriveTaxType(form.buyer.stateCode);
  const taxAmount    = Math.round(taxableValue * (Number(form.taxRate) / 100) * 100) / 100;
  const grandTotal   = Math.round((taxableValue + taxAmount) * 100) / 100;
  const fy           = getFY(form.invoiceDate);

  const previewInvoice = {
    invoiceNumber: form.customInvoice && form.invoiceNumber ? form.invoiceNumber : `(auto — ${fy})`,
    invoiceDate:   form.invoiceDate,
    copyType:      form.copyType,
    poNumber:      form.poNumber,
    transportMode: form.transportMode,
    vehicleNumber: form.vehicleNumber,
    placeOfSupply: form.placeOfSupply,
    seller:        SELLER,
    buyer:         form.buyer,
    consignee:     form.sameAsbuyer ? form.buyer : form.consignee,
    lineItems:     computedItems,
    packing:       form.packing,
    taxableValue,  taxType, taxRate: form.taxRate, taxAmount, grandTotal,
    amountInWords: grandTotal > 0 ? amountInWords(grandTotal) : '',
  };

  // ── Field updaters ───────────────────────────────────────────────────────

  const setField   = (key, val) => setForm(f => ({ ...f, [key]: val }));
  const setBuyer   = (key, val) => setForm(f => ({ ...f, buyer: { ...f.buyer, [key]: val } }));
  const setConsignee = (key, val) => setForm(f => ({ ...f, consignee: { ...f.consignee, [key]: val } }));
  const setPacking = (key, val) => setForm(f => ({ ...f, packing: { ...f.packing, [key]: val } }));

  const setItem = (idx, key, val) => setForm(f => {
    const items = [...f.lineItems];
    items[idx] = { ...items[idx], [key]: val };
    return { ...f, lineItems: items };
  });

  const addItem    = () => setForm(f => ({ ...f, lineItems: [...f.lineItems, defaultItem()] }));
  const removeItem = (idx) => setForm(f => ({ ...f, lineItems: f.lineItems.filter((_, i) => i !== idx) }));

  // Prefill item from product catalogue
  const prefillItem = (idx, stone) => {
    setItem(idx, 'description', stone.name);
    setItem(idx, 'rate', stone.pricePerSqFt);
    setItem(idx, 'hsnCode', '68029900'); // standard HSN for dressed stone
  };

  // ── Validation ────────────────────────────────────────────────────────────

  const validateForm = () => {
    if (!form.invoiceDate) return 'Invoice Date is required.';
    if (!form.buyer.name) return 'Buyer Company Name is required.';
    if (!form.sameAsbuyer && !form.consignee.name) return 'Consignee Name is required.';
    if (form.lineItems.length === 0) return 'At least one line item is required.';
    for (let i = 0; i < form.lineItems.length; i++) {
      const it = form.lineItems[i];
      if (!it.description.trim()) return `Line Item #${i + 1} Description is required.`;
      if (!it.qty || Number(it.qty) <= 0) return `Line Item #${i + 1} Qty must be greater than 0.`;
      if (!it.rate || Number(it.rate) <= 0) return `Line Item #${i + 1} Rate must be greater than 0.`;
    }
    return null;
  };

  // ── Submit ───────────────────────────────────────────────────────────────

  const handleSubmit = useCallback(async (e) => {
    if (e) e.preventDefault();
    
    const valError = validateForm();
    if (valError) {
      setError(valError);
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    setSubmitting(true);
    setError('');
    try {
      const payload = {
        ...form,
        consignee: form.sameAsbuyer ? { ...form.buyer } : form.consignee,
        // Send invoiceNumber only if user set a custom one; otherwise let backend auto-generate
        invoiceNumber: form.customInvoice && form.invoiceNumber.trim() ? form.invoiceNumber.trim() : '',
      };
      delete payload.sameAsbuyer;
      delete payload.customInvoice;

      const res = await authFetch('/api/invoices', {
        method: 'POST',
        body: JSON.stringify(payload),
      });

      if (res.status === 401) { logout(); return; }
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Save failed');
      navigate(`/admin/invoices/${data.invoice._id}`);
    } catch (err) {
      setError(err.message || 'Failed to save invoice');
    } finally {
      setSubmitting(false);
    }
  }, [form, authFetch, logout, navigate]);

  const fmt = (n) => Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  // We use Tailwind classes now.
  const inpClass = "w-full px-3 py-2 rounded-lg border border-stone-300 text-sm bg-white text-stone-900 outline-none transition-all duration-200 focus:border-stone-900 focus:ring-2 focus:ring-stone-900/20 invalid:focus:border-red-500 invalid:focus:ring-red-500/20";
  const labelClass = "block text-[11px] font-bold text-stone-500 uppercase tracking-wider mb-1.5";
  const sectionClass = "bg-white rounded-xl p-6 sm:p-8 mb-6 shadow-sm border border-stone-200 transition-shadow hover:shadow-md";
  const sectionTitleClass = "text-sm font-extrabold text-stone-900 uppercase tracking-widest mb-5 pb-3 border-b border-stone-100";
  const grid2Class = "grid grid-cols-1 sm:grid-cols-2 gap-5";
  const grid3Class = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5";

  // ── Render ───────────────────────────────────────────────────────────────

  if (showPreview) {
    return (
      <div className="min-h-screen bg-stone-50 font-sans">
        {/* Preview toolbar */}
        <div className="no-print bg-stone-900 px-6 py-4 flex items-center gap-4 shadow-md sticky top-0 z-50">
          <button onClick={() => setShowPreview(false)} 
            className="bg-transparent border border-white/20 text-stone-400 px-4 py-2 rounded-md text-sm font-semibold hover:bg-white/10 hover:text-white transition-colors">
            ← Back to Form
          </button>
          <span className="text-stone-500 text-sm font-medium hidden sm:inline">Preview — check before saving</span>
          <div className="ml-auto flex gap-3">
            <button onClick={() => window.print()} 
              className="bg-stone-700 hover:bg-stone-600 text-white border-none px-5 py-2 rounded-lg cursor-pointer text-sm font-bold transition-all shadow-sm active:scale-95">
              🖨 Print Preview
            </button>
            <button onClick={handleSubmit} disabled={submitting} 
              className="bg-green-600 hover:bg-green-500 text-white border-none px-5 py-2 rounded-lg cursor-pointer text-sm font-bold transition-all shadow-sm active:scale-95 disabled:opacity-70 disabled:cursor-not-allowed">
              {submitting ? 'Saving…' : '💾 Save Invoice'}
            </button>
          </div>
        </div>
        {error && <div className="bg-red-50 text-red-600 px-6 py-3 text-sm font-medium border-b border-red-100">{error}</div>}
        <div className="p-8 sm:p-10">
          <InvoicePrint invoice={previewInvoice} />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-stone-50 font-sans">
      {/* Top bar */}
      <div className="no-print bg-stone-900 px-6 py-4 flex items-center justify-between shadow-md sticky top-0 z-50">
        <div className="flex items-center gap-4">
          <Link to="/admin/invoices" className="text-stone-400 hover:text-white text-sm font-medium transition-colors no-underline">
            ← Invoices
          </Link>
          <span className="text-white text-base font-extrabold tracking-tight">New Invoice</span>
        </div>
        <button id="admin-logout-btn-form" onClick={() => { logout(); navigate('/admin/login'); }}
          className="bg-transparent border border-white/20 text-stone-400 px-4 py-2 rounded-md text-sm font-semibold hover:bg-white/10 hover:text-white transition-colors duration-200">
          Logout
        </button>
      </div>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
        <form onSubmit={handleSubmit} id="invoice-form" className="space-y-6">

          {/* ── Invoice Meta ───────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={sectionTitleClass}>Invoice Details</div>
            <div className={grid3Class}>
              <div className="sm:col-span-2 lg:col-span-1">
                <div className="flex items-center justify-between mb-1.5">
                  <span className={labelClass.replace('mb-1.5', '')}>Invoice Number</span>
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={form.customInvoice}
                      onChange={e => setField('customInvoice', e.target.checked)}
                      className="w-3.5 h-3.5 rounded accent-stone-900"
                    />
                    <span className="text-[10px] font-bold text-stone-400 uppercase tracking-wider">
                      {form.customInvoice ? 'Custom' : 'Auto'}
                    </span>
                  </label>
                </div>
                {form.customInvoice ? (
                  <input
                    id="invoice-number"
                    className={inpClass}
                    value={form.invoiceNumber}
                    onChange={e => setField('invoiceNumber', e.target.value)}
                    placeholder={`e.g. 42/${fy}`}
                  />
                ) : (
                  <div className="relative">
                    <input
                      className={`${inpClass} bg-stone-100 text-stone-500 cursor-not-allowed focus:ring-0`}
                      value={`Auto — ${fy}`}
                      readOnly
                    />
                    <span className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[9px] font-bold uppercase tracking-wider bg-stone-300 text-stone-600 px-1.5 py-0.5 rounded">
                      Server
                    </span>
                  </div>
                )}
              </div>
              <div>
                <span className={labelClass}>Invoice Date *</span>
                <input id="invoice-date" type="date" className={inpClass} value={form.invoiceDate}
                  onChange={e => setField('invoiceDate', e.target.value)} required />
              </div>
              <div>
                <span className={labelClass}>Copy Type</span>
                <select id="copy-type" className={inpClass} value={form.copyType}
                  onChange={e => setField('copyType', e.target.value)}>
                  <option>ORIGINAL FOR RECIPIENT</option>
                  <option>DUPLICATE FOR TRANSPORTER</option>
                  <option>TRIPLICATE FOR SUPPLIER</option>
                </select>
              </div>
              <div>
                <span className={labelClass}>PO Number</span>
                <input id="po-number" className={inpClass} value={form.poNumber}
                  onChange={e => setField('poNumber', e.target.value)} placeholder="Optional" />
              </div>
              <div>
                <span className={labelClass}>Transport Mode</span>
                <input id="transport-mode" className={inpClass} value={form.transportMode}
                  onChange={e => setField('transportMode', e.target.value)} />
              </div>
              <div>
                <span className={labelClass}>Vehicle Number</span>
                <input id="vehicle-number" className={inpClass} value={form.vehicleNumber}
                  onChange={e => setField('vehicleNumber', e.target.value)} placeholder="e.g. AP39WC1114" />
              </div>
              <div className="sm:col-span-2 lg:col-span-3">
                <span className={labelClass}>Place of Supply</span>
                <input id="place-of-supply" className={`${inpClass} max-w-sm`} value={form.placeOfSupply}
                  onChange={e => setField('placeOfSupply', e.target.value)} placeholder="e.g. BETAMCHERLA" />
              </div>
            </div>
          </div>

          {/* ── Buyer ──────────────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={sectionTitleClass}>Buyer (Billed To) *</div>
            <div className={grid2Class}>
              <div>
                <span className={labelClass}>Company / Name *</span>
                <input id="buyer-name" className={inpClass} value={form.buyer.name} required
                  onChange={e => setBuyer('name', e.target.value)} placeholder="e.g. GLOBAL IMPEX PVT LTD" />
              </div>
              <div>
                <span className={labelClass}>GSTIN</span>
                <input id="buyer-gstin" className={inpClass} value={form.buyer.gstin}
                  onChange={e => setBuyer('gstin', e.target.value)} placeholder="e.g. 23AADCG1954B1Z6" />
              </div>
              <div className="sm:col-span-2">
                <span className={labelClass}>Address</span>
                <textarea id="buyer-address" className={`${inpClass} resize-y min-h-[80px]`}
                  value={form.buyer.address} onChange={e => setBuyer('address', e.target.value)}
                  placeholder="Full postal address" />
              </div>
              <div>
                <span className={labelClass}>State</span>
                <input id="buyer-state" className={inpClass} value={form.buyer.state}
                  onChange={e => setBuyer('state', e.target.value)} placeholder="e.g. M.P." />
              </div>
              <div>
                <span className={labelClass}>State Code</span>
                <input id="buyer-state-code" className={inpClass} value={form.buyer.stateCode}
                  onChange={e => setBuyer('stateCode', e.target.value)} placeholder="e.g. 23" />
              </div>
            </div>
          </div>

          {/* ── Consignee ──────────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={`${sectionTitleClass} flex justify-between items-center border-none mb-0`}>
              <span>Consignee (Shipped To)</span>
              <label className="flex items-center gap-2 cursor-pointer text-sm font-medium normal-case text-stone-600 hover:text-stone-900 transition-colors">
                <input id="same-as-buyer" type="checkbox" checked={form.sameAsbuyer}
                  className="w-4 h-4 rounded text-stone-900 focus:ring-stone-900 cursor-pointer"
                  onChange={e => setField('sameAsbuyer', e.target.checked)} />
                Same as Buyer
              </label>
            </div>
            {!form.sameAsbuyer && (
              <div className={`${grid2Class} mt-5 pt-5 border-t border-stone-100`}>
                <div>
                  <span className={labelClass}>Name *</span>
                  <input id="consignee-name" className={inpClass} value={form.consignee.name}
                    required={!form.sameAsbuyer}
                    onChange={e => setConsignee('name', e.target.value)} placeholder="e.g. ICBC, MANALI" />
                </div>
                <div>
                  <span className={labelClass}>GSTIN</span>
                  <input id="consignee-gstin" className={inpClass} value={form.consignee.gstin}
                    onChange={e => setConsignee('gstin', e.target.value)} placeholder="e.g. 23AADCG..." />
                </div>
                <div className="sm:col-span-2">
                  <span className={labelClass}>Address</span>
                  <textarea id="consignee-address" className={`${inpClass} resize-y min-h-[80px]`}
                    value={form.consignee.address} onChange={e => setConsignee('address', e.target.value)} />
                </div>
                <div>
                  <span className={labelClass}>State</span>
                  <input id="consignee-state" className={inpClass} value={form.consignee.state}
                    onChange={e => setConsignee('state', e.target.value)} />
                </div>
                <div>
                  <span className={labelClass}>State Code</span>
                  <input id="consignee-state-code" className={inpClass} value={form.consignee.stateCode}
                    onChange={e => setConsignee('stateCode', e.target.value)} placeholder="e.g. 33" />
                </div>
              </div>
            )}
            {form.sameAsbuyer && (
              <p className="text-sm text-stone-500 m-0 mt-2 italic">
                Consignee will be set to buyer details automatically.
              </p>
            )}
          </div>

          {/* ── Line Items ─────────────────────────────────────────── */}
          <div className={`${sectionClass} !p-0 overflow-hidden`}>
            <div className={`${sectionTitleClass} m-6 mb-4`}>Line Items *</div>
            
            <div className="overflow-x-auto px-6 pb-2">
              <table className="w-full text-left border-collapse min-w-[750px]">
                <thead>
                  <tr className="bg-stone-50 border-y border-stone-200">
                    {['#', 'Description *', 'HSN Code', 'Qty *', 'Unit', 'Rate (₹) *', 'Amount (₹)', ''].map((h, i) => (
                      <th key={h} className={`py-3 px-2 text-[11px] font-bold text-stone-500 uppercase tracking-wider ${i === 6 ? 'text-right' : ''}`}>
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-stone-100">
                  {form.lineItems.map((item, idx) => {
                    const amt = Math.round(Number(item.qty || 0) * Number(item.rate || 0) * 100) / 100;
                    return (
                      <tr key={idx} className="group hover:bg-stone-50/50 transition-colors">
                        <td className="py-3 px-2 text-stone-400 font-bold w-8">{idx + 1}</td>
                        <td className="py-3 px-2 min-w-[220px]">
                          <input id={`item-desc-${idx}`} className={`${inpClass} mb-1.5`}
                            value={item.description} required
                            onChange={e => setItem(idx, 'description', e.target.value)}
                            placeholder="Description of goods" />
                          <select className={`${inpClass} !text-xs !py-1.5 !bg-stone-50 text-stone-500`}
                            value="" onChange={e => {
                              if (!e.target.value) return;
                              const stone = PREMIUM_STONES.find(s => s.id === e.target.value);
                              if (stone) prefillItem(idx, stone);
                            }}>
                            <option value="">⚡ Quick-fill from catalogue…</option>
                            {PREMIUM_STONES.map(s => (
                              <option key={s.id} value={s.id}>{s.name}</option>
                            ))}
                          </select>
                        </td>
                        <td className="py-3 px-2 w-28 align-top">
                          <input id={`item-hsn-${idx}`} className={inpClass} value={item.hsnCode}
                            onChange={e => setItem(idx, 'hsnCode', e.target.value)}
                            placeholder="68029900" />
                        </td>
                        <td className="py-3 px-2 w-24 align-top">
                          <input id={`item-qty-${idx}`} type="number" step="0.01" min="0" className={inpClass}
                            value={item.qty} required
                            onChange={e => setItem(idx, 'qty', e.target.value)} />
                        </td>
                        <td className="py-3 px-2 w-20 align-top">
                          <input id={`item-unit-${idx}`} className={inpClass} value={item.unit}
                            onChange={e => setItem(idx, 'unit', e.target.value)} />
                        </td>
                        <td className="py-3 px-2 w-28 align-top">
                          <input id={`item-rate-${idx}`} type="number" step="0.01" min="0" className={inpClass}
                            value={item.rate} required
                            onChange={e => setItem(idx, 'rate', e.target.value)} />
                        </td>
                        <td className="py-3 px-2 w-28 font-bold text-stone-900 text-right align-top pt-5">
                          ₹{fmt(amt)}
                        </td>
                        <td className="py-3 px-2 w-10 text-center align-top pt-4">
                          {form.lineItems.length > 1 && (
                            <button type="button" id={`remove-item-${idx}`}
                              onClick={() => removeItem(idx)}
                              className="text-stone-400 hover:text-red-500 transition-colors p-1 rounded-full hover:bg-red-50"
                              title="Remove item">
                              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                            </button>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>

            <div className="p-6 pt-2">
              <button type="button" id="add-line-item" onClick={addItem}
                className="w-full py-2.5 border-2 border-dashed border-stone-300 rounded-lg text-sm font-bold text-stone-500 hover:text-stone-900 hover:border-stone-400 hover:bg-stone-50 transition-all duration-200">
                + Add Line Item
              </button>
            </div>
          </div>

          {/* ── Tax Settings ───────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={sectionTitleClass}>Tax Settings</div>
            <div className="flex flex-wrap items-center gap-8">
              <div>
                <span className={labelClass}>GST Rate (%)</span>
                <input id="tax-rate" type="number" min="0" max="100" className={`${inpClass} w-24`}
                  value={form.taxRate} onChange={e => setField('taxRate', Number(e.target.value))} />
              </div>
              <div>
                <span className={labelClass}>Tax Type (derived)</span>
                <div className="flex items-center gap-3 mt-1">
                  <span className={`inline-block px-3.5 py-1.5 rounded-lg font-bold text-sm shadow-sm
                    ${taxType === 'IGST' ? 'bg-yellow-100 text-yellow-800 border border-yellow-200' : 'bg-green-100 text-green-800 border border-green-200'}`}>
                    {taxType === 'IGST' ? `IGST @ ${form.taxRate}%` : `CGST ${form.taxRate/2}% + SGST ${form.taxRate/2}%`}
                  </span>
                  <span className="text-xs text-stone-400 italic">
                    (auto: based on buyer state code vs AP)
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* ── Packing ────────────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={sectionTitleClass}>Packing Details</div>
            <div className={grid2Class}>
              <div>
                <span className={labelClass}>Total Crates</span>
                <input id="packing-crates" type="number" min="0" className={inpClass}
                  value={form.packing.totalCrates} onChange={e => setPacking('totalCrates', e.target.value)}
                  placeholder="e.g. 1" />
              </div>
              <div>
                <span className={labelClass}>Pieces per Crate</span>
                <input id="packing-ppc" type="number" min="0" step="0.01" className={inpClass}
                  value={form.packing.piecesPerCrate} onChange={e => setPacking('piecesPerCrate', e.target.value)}
                  placeholder="e.g. 100" />
              </div>
            </div>
          </div>

          {/* ── Notes ─────────────────────────────────────────────── */}
          <div className={sectionClass}>
            <div className={sectionTitleClass}>Notes (optional)</div>
            <textarea id="invoice-notes" className={`${inpClass} resize-y min-h-[90px]`}
              value={form.notes} onChange={e => setField('notes', e.target.value)}
              placeholder="Any additional notes or remarks…" />
          </div>

          {/* ── Live totals panel ──────────────────────────────────── */}
          <div className="bg-stone-900 text-white rounded-xl p-6 sm:p-8 mb-8 shadow-xl relative overflow-hidden">
            {/* Decorative background element */}
            <div className="absolute -right-20 -top-20 w-64 h-64 bg-white/5 rounded-full blur-3xl pointer-events-none"></div>
            
            <div className="text-xs font-bold text-stone-400 uppercase tracking-widest mb-6 border-b border-white/10 pb-3">
              Live Totals Preview
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 relative z-10">
              {[
                ['Taxable Value', `₹${fmt(taxableValue)}`],
                [taxType === 'IGST' ? `IGST (${form.taxRate}%)` : `CGST+SGST (${form.taxRate}%)`, `₹${fmt(taxAmount)}`],
                ['Grand Total', `₹${fmt(grandTotal)}`, 'text-amber-400'],
              ].map(([k, v, colorClass]) => (
                <div key={k} className="bg-white/5 p-4 rounded-lg border border-white/10">
                  <div className="text-xs text-stone-400 mb-1 font-medium">{k}</div>
                  <div className={`text-2xl font-extrabold ${colorClass || 'text-white'}`}>{v}</div>
                </div>
              ))}
            </div>
            {grandTotal > 0 && (
              <div className="mt-4 text-xs text-stone-400 font-medium italic bg-black/20 p-3 rounded-lg border border-black/20">
                {amountInWords(grandTotal)}
              </div>
            )}
          </div>

          {error && (
            <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-5 py-4 rounded-lg text-sm font-medium mb-6 flex items-center gap-3 animate-pulse">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
              {error}
            </div>
          )}

          {/* ── Action buttons ─────────────────────────────────────── */}
          <div className="flex gap-4 justify-end pb-12 sticky bottom-0 bg-stone-50/90 backdrop-blur-md pt-4 z-40 border-t border-stone-200 mt-8 px-4 -mx-4 sm:px-0 sm:mx-0 sm:border-none sm:bg-transparent">
            <button type="button" id="preview-btn" onClick={() => {
              const valError = validateForm();
              if (valError) {
                setError(valError);
                window.scrollTo({ top: 0, behavior: 'smooth' });
              } else {
                setError('');
                setShowPreview(true);
              }
            }}
              className="bg-stone-800 hover:bg-stone-700 text-white border-none px-6 py-3 rounded-lg cursor-pointer text-sm font-bold transition-all shadow-md hover:shadow-lg active:scale-95 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
              Preview
            </button>
            <button type="submit" id="save-invoice-btn" disabled={submitting}
              className="bg-green-600 hover:bg-green-500 text-white border-none px-8 py-3 rounded-lg cursor-pointer text-sm font-bold transition-all shadow-md hover:shadow-lg active:scale-95 disabled:opacity-70 disabled:cursor-not-allowed flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg>
              {submitting ? 'Saving…' : 'Save Invoice'}
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
